version: '3.4'

services:
  php:
    image: php:7.2-cli-alpine
    command: /bin/sh
    working_dir: /data/app
    ports:
        - "8000:80"
    volumes:
        - ./:/data:cached

  node:
    image: node:8-alpine
    command: /bin/sh
    working_dir: /data/app
    volumes:
        - ./:/data:cached